### PR TITLE
metanorma/metanorma-build-scripts#65 Update GHA configs

### PR DESCRIPTION
**Pull request by CAMOBAP**
As title. 

 _Generated by Cimas_.

### CODE REVIEW

**Comment by CAMOBAP** [comment]
I have checked tests and looks like behavior changed because the new nokogiri version, I have update tests to work with both versions of nokogiri

@opoudjis @ronaldtse could you please have a look, because I'm not sure that I did it in the right way?

**Comment by opoudjis** [comment]
I am going to have to understand what Nokogiri 1.11 is doing with >, so I'll check this, thank you.

**Comment by opoudjis** [comment]
Oh, I ended up dealing with this myself, so closing this.

**Comment by opoudjis** [comment]
Oops, no, I just need to overwrite your spec changes.

**Pull request merged**
